const products = [
    {
        _id: '1',
        name: 'Nguyen Thanh Phu',
        image: '/images/airpods.jpg',
        description: 'hahahaha',
        brand:'Apple',
        category: 'ellectro',
        price: 50,
        countInStock: 0,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '2',
        name: 'Nguyen Thanh Phu',
        image: '/images/airpods.jpg',
        description: 'hahahaha',
        brand:'Apple',
        category: 'ellectro',
        price: 50,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '3',
        name: 'Nguyen Thanh Phu',
        image: '/images/airpods.jpg',
        description: 'hahahaha',
        brand:'Apple',
        category: 'ellectro',
        price: 50,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '4',
        name: 'Nguyen Thanh Phu',
        image: '/images/airpods.jpg',
        description: 'hahahaha',
        brand:'Apple',
        category: 'ellectro',
        price: 50,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
]
export default products